services:
  aspnetcoremongoapi:
    image: ${DOCKER_REGISTRY-}aspnetcoremongoapi
    ports:
      - 8081:8081
    build:
      context: .
      dockerfile: AspNetCoreMongoApi/Dockerfile
    environment:
       - CorsOptions__AllowedOrigins__0=http://localhost:5173
       - CorsOptions__AllowedOrigins__1=http://localhost:5174

       - "DbOptions__ConnectionString=User Id=postgres;Password=pwd;Server=db;Port=5432;Database=db"
      
       - "AuthenticationOptions__MetadataAddress=http://keycloak:8080/realms/auth_demo/.well-known/openid-configuration"
       - "AuthenticationOptions__ValidIssuer=http://localhost:8080/realms/auth_demo"
       - "AuthenticationOptions__AuthorizationUrl=http://localhost:8080/realms/auth_demo/protocol/openid-connect/auth"
       - "AuthenticationOptions__TokenUrl=http://localhost:8080/realms/auth_demo/protocol/openid-connect/token"
       - "AuthenticationOptions__RefreshUrl=http://localhost:8080/realms/auth_demo/protocol/openid-connect/token"
       - "AuthenticationOptions__Audience=${AUTHENTICATION_AUDIENCE}"
       - "AuthenticationOptions__ClientId=${AUTHENTICATION_CLIENTID}"
       - "AuthenticationOptions__RequireHttps=false"
       - "AuthenticationOptions__Scopes__public-client-audience-scope=public-client-audience-scope"
       - "AuthenticationOptions__Scopes__profile=profile"
       - "AuthenticationOptions__Scopes__openid=openid"

       - "KeycloakClientOptions__Secret=0irV27QfnSdCUPQvhE2dH4JgMaxkbueB"
       - "KeycloakClientOptions__Realm=auth_demo"
       - "KeycloakClientOptions__ClientId=service-client"
       - "KeycloakClientOptions__AuthServerUrl=http://keycloak:8080/"

       - "SeqOptions__Url=seq-dashboard:5341"
       - "OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf"
       - "OTEL_EXPORTER_OTLP_HEADERS=X-Seq-ApiKey=${X_SEQ_API_KEY_HEADER}"

       - "RedisOptions__Configuration=redis:6379,password=${REDIS_PASSWORD},abortConnect=false" 
       - "RedisOptions__Password=${REDIS_PASSWORD}"

       - "ElasticSearchOptions__Url=http://elasticsearch:9200"
       - "ElasticSearchOptions__LocalUsername=elasticsearch"
       - "ElasticSearchOptions__LocalPassword=elasticsearch"
       - "ElasticSearchOptions__IsSslUsed=false"
  
  keycloak:
    image: quay.io/keycloak/keycloak:26.5.2
    container_name: keycloak
    command: start-dev --import-realm
    volumes:
    - ./keycloak-imports:/opt/keycloak/data/import:ro
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HEALTH_ENABLED: true
      KC_DB: postgres
      KC_DB_URL_HOST: postgres_keycloak
      KC_DB_URL_DATABASE: ${KEYCLOAK_DB}
      KC_DB_USERNAME: ${KEYCLOAK_DB_USERNAME}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KEYCLOAK_IMPORT: /opt/jboss/keycloak/imports/realm-export.json -Dkeycloak.profile.feature.upload_scripts=enabled
    ports:
    - 8080:8080

  postgres_keycloak:
    container_name: postgres_keycloak
    image: postgres:19beta1
    environment:
      POSTGRES-DB: ${KEYCLOAK_DB}
      POSTGRES_USER: ${KEYCLOAK_DB_USERNAME}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    volumes:
      - postgres-keycloak-data:/var/lib/postgresql

  db:
    container_name: db
    image: postgres:19beta1
    environment:
      POSTGRES-DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pwd
    volumes:
      - postgres-db-data:/var/lib/postgresql

  redis:
    image: redis:7.2-alpine
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis-data:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

  redis-insight:
    image: redis/redisinsight:3.4
    restart: always
    ports:
      - "5540:5540"
    volumes:
      - redis-insight:/data

  seq-dashboard:
    image: datalust/seq:2025.2
    volumes:
      - seq-data:/data:2025.2
    environment:
      - ACCEPT_EULA=Y
      - SEQ_PASSWORD=${SEQ_PASSWORD}
      - SEQ_FIRSTRUN_ADMINPASSWORDHASH=${SEQ_FIRSTRUN_ADMINPASSWORDHASH}
      - SEQ_API_CANONICALURI=https://seq.example.com
    ports:
      - 5341:5341
      - 8083:80
  elasticsearch:
    image: elasticsearch:9.4.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false  # Disable auth for local dev
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
  kibana:
    image: kibana:9.4.2
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_URL: elasticsearch:9200

volumes:
  postgres-keycloak-data:
  mongodb1-data:
  mongodb2-data:
  mongodb3-data:
  mongo-express-data:
  seq-data:
  redis-data:
  redis-config:
  redis-insight:
  elasticsearch-data:
  postgres-db-data:
   