apiVersion: v1
kind: Service
metadata:
  name: weather-forecast-service
spec:
  type: LoadBalancer
  selector:
    app: weather-forecast-service
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30010
