image:
  tag: 2025.2
firstRunAdminUsername: admin
firstRunAdminPasswordSecret:
  name: seq-secret
  key: password
baseURI: https://test.mytest.com
extraVolumes:
- name: certificatesvolume
  secret:
    secretName: tls-seq-certificates-secret

extraVolumeMounts:
- name: certificatesvolume
  mountPath: /data/Certificates
extraEnvs:
  - name: SEQ_API_LISTENURIS
    value: "https://localhost:443,https://localhost:45341"
  - name: SEQ_API_REDIRECTHTTPTOHTTPS
    value: "true"
  - name: SEQ_CERTIFICATES_DEFAULTPASSWORD
    valueFrom:
      secretKeyRef:
        name: tls-pfx-password-secret
        key: password
