apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: backend-tls
spec:
  targetRefs:
  - group: ''
    kind: Service
    name: mongo-express-service
  - group: ''
    kind: Service
    name: weather-forecast-service
  - group: ''
    kind: Service
    name: seq
  validation:
    caCertificateRefs:
    - name: tls-key-and-certificate-configmap
      group: ''
      kind: ConfigMap
    hostname: test.mytest.com
